[tool.poetry]
name = "usd_search_client"
version = "1.2.0"
description = "USD Search and Asset Graph Search APIs"
authors = ["NVIDIA"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/NVIDIA-Omniverse/usdsearch-client"
keywords = ["OpenAPI", "USD Search", "Asset Graph Search", "OpenUSD", "Omniverse"]
include = ["usd_search_client/py.typed"]

[tool.poetry.dependencies]
python = "^3.8"

urllib3 = ">=1.25.3"
python-dateutil = ">=2.8.2"
aiohttp = ">=3.8.4"
aiohttp-retry = ">=2.8.3"
pydantic = ">=2"
typing-extensions = ">=4.7.1"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.2.1"
tox = ">=3.9.0"
flake8 = ">=4.0.0"
types-python-dateutil = ">=2.8.19.14"
mypy = "1.4.1"
pillow = ">=10.0.0"
pytest-asyncio = ">=0.24.0"
pytest-cov = ">=5.0.0"
pytest-timeout = ">=2.4.0"
coverage = "7.6.0"
pytest-xdist = ">=3.6.1"
pdoc = ">=14.1.0"


[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
pattern = "default-unprefixed"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[tool.mypy]
files = [
  "usd_search_client",
  "tests", # hand-written tests
]

# List from: https://mypy.readthedocs.io/en/stable/existing_code.html#introduce-stricter-options
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true

## Getting these passing should be easy
strict_equality = true
strict_concatenate = true

## Strongly recommend enabling this one as soon as you can
check_untyped_defs = true

## These shouldn't be too much additional work, but may be tricky to
## get passing if you use a lot of untyped libraries
disallow_subclassing_any = true
disallow_untyped_decorators = true
disallow_any_generics = true

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-v --timeout 30 --color yes --cov-report term --cov-report html --cov-report xml --cov-config=./.coveragerc --cov=./"
testpaths = ["tests"]